### ISSUE TITLE
[WordCamp] Jinja, Uganda

### ISSUE THREAD

**Issue by felipevelzani** [WordPress/Community-Team#328] opened 2024-10-21 12:37 UTC
### Event Name:

Jinja, Uganda
### Event Type:

WordCamp
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8232077&action=edit

Found WordCamp application for "Jinja, Uganda".

**Comment by nukaga** [comment] 2024-10-23 04:51
I'll close this as it seems to be a duplicate of [WordCamp] Jinja, Uganda #320

**Closed as completed by nukaga** 2024-10-23 04:51 UTC
Labels: Awaiting Triage, application, wordcamp-application, WordCamp, event
